<script>
import PageHero from '../components/PageHero.vue'
import services from '../data/services.json'
import hospitalInfo from '../data/hospital-info.json'
import emailService from '../services/emailService.js'

export default {
  name: 'AppointmentPage', components: { PageHero },
  data() { return { services, info: hospitalInfo, form: { fullName: '', email: '', phone: '', service: '', preferredDate: '', message: '' }, loading: false, feedback: '', success: false, minDate: this.minimumDate() } },
  methods: {
    minimumDate() { const date = new Date(); date.setHours(date.getHours() + 24); const pad = value => String(value).padStart(2, '0'); return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}` },
    async submit() { this.loading = true; this.feedback = ''; try { const result = await emailService.sendAppointmentEmail(this.form); this.success = result.success; this.feedback = result.message; if (result.success) this.form = { fullName: '', email: '', phone: '', service: '', preferredDate: '', message: '' } } catch { this.success = false; this.feedback = 'We could not send your request. Please call us or try again.' } finally { this.loading = false } }
  }
}
</script>
<template><main><PageHero eyebrow="Appointments" title="Book your visit to BSH" description="Tell us what you need and our team will call to confirm your appointment. For emergencies, please come directly to the hospital or call us." />
  <section class="section appointment-page"><div class="site-container appointment-page__grid"><div><div class="section-heading"><p class="eyebrow">Request an appointment</p><h2>Choose a convenient time</h2><p>Complete the form below. This is a request; our front desk will contact you to confirm availability.</p></div><form @submit.prevent="submit"><p v-if="feedback" class="feedback" :class="success?'success':'error'" role="status">{{ feedback }}</p><div class="field-row"><label>Full name *<input v-model.trim="form.fullName" required autocomplete="name"></label><label>Phone number *<input v-model.trim="form.phone" required type="tel" autocomplete="tel"></label></div><div class="field-row"><label>Email address *<input v-model.trim="form.email" required type="email" autocomplete="email"></label><label>Service *<select v-model="form.service" required><option value="" disabled>Select a service</option><option v-for="service in services" :key="service.id" :value="service.title">{{ service.title }}</option></select></label></div><label>Preferred date and time *<input v-model="form.preferredDate" required type="datetime-local" :min="minDate"></label><label>Anything we should know?<textarea v-model.trim="form.message" rows="5" placeholder="Symptoms, preferred doctor or other helpful information"></textarea></label><button type="submit" class="button-primary" :disabled="loading"><i class="bi bi-calendar-check"></i>{{ loading ? 'Sending request…' : 'Request appointment' }}</button></form></div>
  <aside><div class="appointment-help"><i class="bi bi-heart-pulse-fill"></i><h2>Emergency?</h2><p>Our emergency department is open 24 hours a day, seven days a week.</p><a href="tel:+2347033449959"><i class="bi bi-telephone"></i> +234 703 344 9959</a></div><div class="visit-info"><h2>Before your visit</h2><ul><li><i class="bi bi-check2-circle"></i>Bring a valid ID and any medical records.</li><li><i class="bi bi-check2-circle"></i>Arrive 15 minutes before your appointment.</li><li><i class="bi bi-check2-circle"></i>Bring a list of current medications.</li><li><i class="bi bi-check2-circle"></i>Our team will confirm your appointment first.</li></ul></div></aside></div></section>
</main></template>
<style scoped>.appointment-page{background:var(--mist)}.appointment-page__grid{display:grid;grid-template-columns:minmax(0,1.25fr) 360px;gap:4rem;align-items:start}.appointment-page form{display:grid;gap:1rem;padding:2rem;border:1px solid var(--line);border-radius:24px;background:#fff;box-shadow:0 12px 30px rgba(13,52,79,.08)}.field-row{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.appointment-page label{display:grid;gap:.4rem;color:#385369;font-size:.78rem;font-weight:800}.appointment-page input,.appointment-page select,.appointment-page textarea{width:100%;padding:.8rem .9rem;border:1px solid var(--line);border-radius:11px;background:#fff;color:var(--ink);outline:none}.appointment-page input:focus,.appointment-page select:focus,.appointment-page textarea:focus{border-color:var(--sky);box-shadow:0 0 0 3px rgba(43,145,201,.13)}.appointment-page button{width:max-content;border:0;cursor:pointer}.appointment-page button:disabled{opacity:.65}.feedback{padding:.8rem 1rem;border-radius:11px;font-size:.82rem;font-weight:700}.feedback.success{background:#e5f7ee;color:#087548}.feedback.error{background:#fce8e9;color:#a42c33}.appointment-page aside{display:grid;gap:1rem}.appointment-help,.visit-info{padding:1.7rem;border-radius:20px}.appointment-help{background:var(--emergency);color:#fff}.appointment-help>i{font-size:1.5rem}.appointment-help h2,.visit-info h2{margin:.7rem 0 .5rem;font:700 1.2rem Sora,sans-serif}.appointment-help p{color:#ffe8ea;font-size:.86rem}.appointment-help a{font-weight:800}.visit-info{border:1px solid var(--line);background:#fff}.visit-info ul{display:grid;gap:.8rem;margin:1rem 0 0;padding:0;list-style:none}.visit-info li{display:flex;gap:.55rem;color:var(--muted);font-size:.8rem}.visit-info i{color:var(--aqua)}@media(max-width:850px){.appointment-page__grid{grid-template-columns:1fr;gap:2rem}.appointment-page aside{grid-template-columns:1fr 1fr}}@media(max-width:600px){.field-row,.appointment-page aside{grid-template-columns:1fr}.appointment-page form{padding:1.2rem}}</style>
