<script>
import PageHero from '../components/PageHero.vue'
const groups=[
  ['Appointments',[['How do I book an appointment at BSH?','You can book online, call our front desk on +234 703 344 9959, or send us a WhatsApp message. Every online request is confirmed by phone.'],['Can I walk in without an appointment?','Yes. Walk-ins are welcome, although booking ahead helps reduce your waiting time.'],['What should I bring to my first appointment?','Please bring a valid ID, your HMO card if applicable, and any relevant referral letters, test results or medication information.'],['Can I reschedule or cancel an appointment?','Please call the front desk as soon as possible so we can offer the time to another patient.']]],
  ['General',[['What are your opening hours?','Clinic hours are Monday to Friday, 8:00 AM to 9:00 PM, and Saturday, 9:00 AM to 6:00 PM. Our emergency department is open 24 hours daily.']]],
  ['Payment',[['Do you accept HMO and health insurance?','We work with a range of HMO partners. Contact our front desk before your visit to confirm your cover.'],['What payment methods do you accept?','Our front desk can confirm the available payment options and any HMO co-payment before your consultation.']]],
  ['Records',[['How do I request a copy of my medical records?','Make a request at the front desk with valid identification. Our team will guide you through the process.']]],
  ['Services',[['When should I register for antenatal care?','Register as soon as you know you are pregnant, so our obstetrics team can support you from the earliest stage.'],['Do you treat children?','Yes. Our family-health team provides compassionate care for children and adults.']]],
  ['Emergency',[['What should I do in a medical emergency?','Come straight to the hospital or call +234 703 344 9959. Our emergency department is open 24 hours, seven days a week.']]],
  ['Facilities',[['Is parking available?','Yes, we provide free on-site parking for patients and visitors.']]],
]
export default {components:{PageHero},data:()=>({groups,open:null}),methods:{toggle(id){this.open=this.open===id?null:id}}}
</script>
<template><main class="faq-page"><PageHero eyebrow="Help centre" title="Frequently asked questions" description="Everything patients usually ask before their first visit — appointments, payment, HMO cover and emergencies."/><section class="section"><div class="site-container faq-list"><section v-for="([title,questions]) in groups" :key="title"><h2>{{ title }}</h2><article v-for="([question,answer],index) in questions" :key="question"><button @click="toggle(`${title}-${index}`)" :aria-expanded="open===`${title}-${index}`"><span>{{ question }}</span><i :class="open===`${title}-${index}`?'bi bi-dash-lg':'bi bi-plus-lg'"></i></button><div v-show="open===`${title}-${index}`"><p>{{ answer }}</p></div></article></section><aside><h2>Still have a question?</h2><p>Our front desk is happy to help on <a href="tel:+2347033449959">+234 703 344 9959</a>.</p><router-link to="/contact" class="button-primary">Contact us</router-link><a class="whatsapp" href="https://wa.me/2347033449959" target="_blank" rel="noopener">Chat on WhatsApp</a></aside></div></section></main></template>
<style scoped>.faq-list{max-width:900px}.faq-list section{margin-bottom:2.2rem}.faq-list section>h2{margin:0 0 .4rem;font-family:Sora,sans-serif;font-size:1rem;color:var(--blue)}.faq-list article{border-bottom:1px solid var(--line)}.faq-list button{display:flex;width:100%;align-items:center;justify-content:space-between;gap:1rem;padding:1.05rem 0;border:0;background:transparent;color:var(--ink);text-align:left;font-size:.9rem;font-weight:800;cursor:pointer}.faq-list button i{color:var(--blue);font-size:.8rem}.faq-list article div{padding:0 2.2rem 1.1rem 0}.faq-list article p{margin:0;color:var(--muted);font-size:.83rem}.faq-list aside{margin-top:3.5rem;padding:2rem;border-radius:20px;background:var(--mist);text-align:center}.faq-list aside h2{margin:0;font-family:Sora,sans-serif;font-size:1.45rem;letter-spacing:-.04em}.faq-list aside p{color:var(--muted);font-size:.85rem}.faq-list aside p a{color:var(--blue);font-weight:800}.faq-list aside a{margin:.4rem}.whatsapp{display:inline-flex;padding:.86rem 1.25rem;color:var(--success);font-size:.82rem;font-weight:800}@media(max-width:500px){.faq-list aside a{display:flex;margin:.8rem 0;justify-content:center}}</style>
