<script>
import PageHero from '../components/PageHero.vue'
import homeImage from '../assets/home-bsh.jpg'; import careImage from '../assets/home-bsh2.jpg'; import doctorImage from '../assets/bg-doc.jpg'; import hospitalImage from '../assets/bg-bsh.jpeg'
const photos=[
  [homeImage,'Facilities','Reception area at Base Specialist Hospital'],[careImage,'Waiting Area','Patient waiting area with natural light'],[doctorImage,'Consultation Rooms','Private consultation room with examination couch'],[hospitalImage,'Equipment','Diagnostic imaging and monitoring equipment'],[homeImage,'Medical Team','Doctors and nurses of Base Specialist Hospital'],[doctorImage,'Departments','Surgical team in the operating theatre'],[careImage,'Consultation Rooms','Antenatal ultrasound consultation'],[hospitalImage,'Equipment','Hospital laboratory diagnostics'],[homeImage,'Departments','Emergency department entrance'],[hospitalImage,'Facilities','Base Specialist Hospital building'],[doctorImage,'Consultation Rooms','Inside Base Specialist Hospital'],[careImage,'Waiting Area','A family consultation in progress'],
]
export default {components:{PageHero},data:()=>({photos,filter:'All',selected:null}),computed:{categories(){return ['All',...new Set(this.photos.map(([,category])=>category))]},filtered(){return this.filter==='All'?this.photos:this.photos.filter(([,category])=>category===this.filter)}},methods:{close(){this.selected=null}}}
</script>
<template><main class="gallery-page"><PageHero eyebrow="Gallery" title="Inside Base Specialist Hospital" description="A calm, clean and well-equipped environment — exactly what you will find when you arrive."/><section class="section"><div class="site-container"><div class="gallery-filters"><button v-for="category in categories" :key="category" :class="{active:filter===category}" @click="filter=category">{{ category }}</button></div><div class="gallery-grid"><button v-for="([image,category,alt],index) in filtered" :key="`${alt}-${index}`" class="gallery-item" @click="selected={image,alt}"><img :src="image" :alt="alt" loading="lazy"><span>{{ alt }}</span></button></div></div></section><div v-if="selected" class="lightbox" role="dialog" aria-modal="true" :aria-label="selected.alt" @click.self="close"><button aria-label="Close image" @click="close"><i class="bi bi-x-lg"></i></button><img :src="selected.image" :alt="selected.alt"></div></main></template>
<style scoped>.gallery-filters{display:flex;justify-content:center;flex-wrap:wrap;gap:.55rem;margin-bottom:2.2rem}.gallery-filters button{padding:.55rem .9rem;border:1px solid var(--line);border-radius:999px;background:#fff;color:var(--muted);font-size:.76rem;font-weight:800;cursor:pointer}.gallery-filters button.active,.gallery-filters button:hover{border-color:var(--blue);background:var(--blue);color:#fff}.gallery-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.gallery-item{position:relative;min-height:240px;padding:0;border:0;border-radius:16px;overflow:hidden;background:var(--mist);cursor:zoom-in}.gallery-item:nth-child(5n+1){grid-row:span 2;min-height:496px}.gallery-item img{width:100%;height:100%;object-fit:cover;transition:.35s}.gallery-item span{position:absolute;inset:auto 0 0;padding:2.2rem 1rem .9rem;color:#fff;text-align:left;background:linear-gradient(transparent,rgba(4,26,45,.8));font-size:.76rem;font-weight:700;opacity:0;transition:.25s}.gallery-item:hover img{transform:scale(1.05)}.gallery-item:hover span{opacity:1}.lightbox{position:fixed;inset:0;z-index:200;display:grid;place-items:center;padding:2rem;background:rgba(3,21,38,.9)}.lightbox img{max-width:min(100%,1000px);max-height:85vh;border-radius:12px}.lightbox button{position:absolute;top:1rem;right:1rem;width:42px;height:42px;border:0;border-radius:50%;background:#fff;color:var(--ink);cursor:pointer}@media(max-width:700px){.gallery-grid{grid-template-columns:repeat(2,1fr)}.gallery-item,.gallery-item:nth-child(5n+1){min-height:190px;grid-row:auto}.gallery-item span{opacity:1}}</style>
